name: Prod Deployment

on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install the deps
        run: npm i eslint eslint-config-react-app eslint-loader eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks
      - name: run the tests
        run: npm run test
        
  build:
    env:
      HEROKU_APP: geokit-app
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: login to heroku
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_USERNAME" >> ~/.netrc
        echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        cat ~/.netrc
        echo $HEROKU_PASSWORD | docker login $HEROKU_REGISTRY -u $HEROKU_USERNAME --password-stdin

    - name: create proper dockerfile
      run: cp Dockerfile.production Dockerfile

    - name: push the docker image to heroku
      run: |
        heroku container:push -a $HEROKU_APP web
        heroku container:release web -a $HEROKU_APP
