# This is a basic workflow to help you get started with Actions

name: How do we deploy stuff?

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install the deps
        run: npm i
      - name: run the tests
        run: npm run test
        
  build:
    env:
      DOCKER_REGISTRY: ntatko/geokit-app
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: login to docker
      run: docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: build the docker image
      run: docker build -t $DOCKER_REGISTRY:$GITHUB_SHA -t $CONTAINER_IMAGE:latest .
    
    - name: push the docker image
      run: |
        docker push $DOCKER_REGISTRY:$GITHUB_SHA
        docker push $DOCKER_REGISTRY:latest

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: just a test
        run: echo testing
