# This is a basic workflow to help you get started with Actions

name: How do we deploy stuff?

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install the deps
        run: npm i eslint eslint-config-react-app eslint-loader eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks
      - name: run the tests
        run: npm run test
        
  build:
    env:
      DOCKER_REGISTRY: ntatko/geokit-app
      HEROKU_REGISTRY: registry.heroku.com
      HEROKU_APP: geokit-app
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: login to docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: login to heroku
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_USERNAME" >> ~/.netrc
        echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        cat ~/.netrc
        echo $HEROKU_PASSWORD | docker login $HEROKU_REGISTRY -u $HEROKU_USERNAME --password-stdin
    
    - name: build the docker image
      run: docker build -t $DOCKER_REGISTRY:$GITHUB_SHA -t $DOCKER_REGISTRY:latest -t $HEROKU_REGISTRY/$HEROKU_APP:$GITHUB_SHA -t $HEROKU_REGISTRY/$HEROKU_APP:latest .
    
    - name: push the docker image to docker
      run: |
        docker push $DOCKER_REGISTRY:$GITHUB_SHA
        docker push $DOCKER_REGISTRY:latest

    - name: push the docker image to heroku
      run: |
        heroku container:push -a $HEROKU_APP web
        docker push $HEROKU_REGISTRY/$HEROKU_APP:$GITHUB_SHA
        docker push $HEROKU_REGISTRY/$HEROKU_APP:latest
        heroku container:release web -a $HEROKU_APP
