
name: NP-DEPLOY

on:
  push:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'
      - 'build/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install the deps
        run: npm i eslint eslint-config-react-app eslint-loader eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y eslint-plugin-react eslint-plugin-react-hooks
      - name: run the tests
        run: npm run test
        
  build:
    env:
      HEROKU_REGISTRY: registry.heroku.com
      HEROKU_APP: geokit-app-np
      HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
      HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: login to heroku
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_PASSWORD: ${{ secrets.HEROKU_PASSWORD }}
      run: |
        echo "machine api.heroku.com" > ~/.netrc
        echo "  login $HEROKU_USERNAME" >> ~/.netrc
        echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        cat ~/.netrc
        echo $HEROKU_PASSWORD | docker login $HEROKU_REGISTRY -u $HEROKU_USERNAME --password-stdin
    
    - name: build and push the docker image to heroku
      run: |
        heroku container:push -a $HEROKU_APP web
        heroku container:release web -a $HEROKU_APP
